import type { DraftFlowStep, DraftAiPresetKey, PatchWeightPresetKey, WeightConfig } from "./types"

export const DRAFT_FLOW: DraftFlowStep[] = [
    { type: "ban", visualSide: "blue", index: 0, label: "Blue Ban 1" },
    { type: "ban", visualSide: "red", index: 0, label: "Red Ban 1" },
    { type: "ban", visualSide: "blue", index: 1, label: "Blue Ban 2" },
    { type: "ban", visualSide: "red", index: 1, label: "Red Ban 2" },
    { type: "ban", visualSide: "blue", index: 2, label: "Blue Ban 3" },
    { type: "ban", visualSide: "red", index: 2, label: "Red Ban 3" },

    { type: "pick", visualSide: "blue", index: 0, label: "Blue Pick 1" },
    { type: "pick", visualSide: "red", index: 0, label: "Red Pick 1" },
    { type: "pick", visualSide: "red", index: 1, label: "Red Pick 2" },
    { type: "pick", visualSide: "blue", index: 1, label: "Blue Pick 2" },
    { type: "pick", visualSide: "blue", index: 2, label: "Blue Pick 3" },
    { type: "pick", visualSide: "red", index: 2, label: "Red Pick 3" },

    { type: "ban", visualSide: "red", index: 3, label: "Red Ban 4" },
    { type: "ban", visualSide: "blue", index: 3, label: "Blue Ban 4" },
    { type: "ban", visualSide: "red", index: 4, label: "Red Ban 5" },
    { type: "ban", visualSide: "blue", index: 4, label: "Blue Ban 5" },

    { type: "pick", visualSide: "red", index: 3, label: "Red Pick 4" },
    { type: "pick", visualSide: "blue", index: 3, label: "Blue Pick 4" },
    { type: "pick", visualSide: "blue", index: 4, label: "Blue Pick 5" },
    { type: "pick", visualSide: "red", index: 4, label: "Red Pick 5" },
]

export const MAX_SERIES_GAMES = 5
export const PATCH_WEIGHT_MAX_PATCHES = 6
export const DEFAULT_PATCH_WEIGHTS = [100, 70, 45, 25, 15, 10]

export const PATCH_WEIGHT_PRESETS: Record<PatchWeightPresetKey, { label: string; weights: number[] }> = {
    balanced: {
        label: "Balanced",
        weights: DEFAULT_PATCH_WEIGHTS,
    },
    currentFocused: {
        label: "Aktueller Patch",
        weights: [100, 55, 30, 15, 5, 0],
    },
    stable: {
        label: "Meta stabil",
        weights: [100, 85, 70, 55, 40, 25],
    },
    currentOnly: {
        label: "Nur aktuell",
        weights: [100, 0, 0, 0, 0, 0],
    },
}

export const DEFAULT_WEIGHTS: WeightConfig = {
    draftPriority: 40,
    roleStats: 20,
    synergy: 15,
    matchup: 20,
    winRate: 5,
    sampleSize: 0,
}

export const WEIGHT_PRESETS: Record<DraftAiPresetKey, { label: string; weights: WeightConfig }> = {
    balanced: {
        label: "Balanced",
        weights: DEFAULT_WEIGHTS,
    },
    counterpick: {
        label: "Counterpick",
        weights: {
            draftPriority: 20,
            roleStats: 15,
            synergy: 10,
            matchup: 45,
            winRate: 5,
            sampleSize: 5,
        },
    },
    synergy: {
        label: "Synergy",
        weights: {
            draftPriority: 20,
            roleStats: 15,
            synergy: 45,
            matchup: 10,
            winRate: 5,
            sampleSize: 5,
        },
    },
    meta: {
        label: "Meta Priority",
        weights: {
            draftPriority: 60,
            roleStats: 20,
            synergy: 5,
            matchup: 10,
            winRate: 5,
            sampleSize: 0,
        },
    },
    safe: {
        label: "Safe / High Confidence",
        weights: {
            draftPriority: 25,
            roleStats: 25,
            synergy: 10,
            matchup: 10,
            winRate: 10,
            sampleSize: 20,
        },
    },
}

export const FRONTLINE_CHAMPIONS = new Set([
    "aatrox",
    "alistar",
    "braum",
    "ksante",
    "leona",
    "malphite",
    "maokai",
    "nautilus",
    "ornn",
    "poppy",
    "rell",
    "renekton",
    "rakan",
    "sejuani",
    "shen",
    "sion",
    "tahmkench",
    "taric",
    "zac",
])

export const ENGAGE_CHAMPIONS = new Set([
    "alistar",
    "amumu",
    "ashe",
    "gnar",
    "gragas",
    "jarvaniv",
    "leona",
    "malphite",
    "maokai",
    "nautilus",
    "neeko",
    "ornn",
    "rakan",
    "rell",
    "sejuani",
    "vi",
    "wukong",
])

export const AP_DAMAGE_CHAMPIONS = new Set([
    "ahri",
    "akali",
    "annie",
    "azir",
    "brand",
    "cassiopeia",
    "corki",
    "diana",
    "elise",
    "fiddlesticks",
    "galio",
    "gragas",
    "gwen",
    "hwei",
    "karma",
    "karthus",
    "kennen",
    "leblanc",
    "lillia",
    "lissandra",
    "lux",
    "malzahar",
    "neeko",
    "nidalee",
    "orianna",
    "rumble",
    "ryze",
    "seraphine",
    "sylas",
    "syndra",
    "taliyah",
    "twistedfate",
    "veigar",
    "viktor",
    "vladimir",
    "xerath",
    "ziggs",
    "zoe",
])

export const AD_DAMAGE_CHAMPIONS = new Set([
    "aatrox",
    "akshan",
    "aphelios",
    "ashe",
    "belveth",
    "caitlyn",
    "camille",
    "darius",
    "draven",
    "ezreal",
    "fiora",
    "gangplank",
    "gnar",
    "graves",
    "irelia",
    "jarvaniv",
    "jax",
    "jayce",
    "jinx",
    "kaisa",
    "kalista",
    "khazix",
    "kindred",
    "leesin",
    "lucian",
    "missfortune",
    "nilah",
    "nocturne",
    "olaf",
    "pantheon",
    "pyke",
    "qiyana",
    "quinn",
    "reksai",
    "renekton",
    "rengar",
    "samira",
    "senna",
    "sivir",
    "tristana",
    "tryndamere",
    "twitch",
    "varus",
    "vayne",
    "vi",
    "viego",
    "xayah",
    "xinzhao",
    "yasuo",
    "yone",
    "zeri",
    "ziggs",
])

export const POKE_CHAMPIONS = new Set([
    "ashe",
    "caitlyn",
    "ezreal",
    "hwei",
    "jayce",
    "karma",
    "lux",
    "maokai",
    "nidalee",
    "orianna",
    "seraphine",
    "varus",
    "velkoz",
    "xerath",
    "ziggs",
    "zoe",
])

export const PICK_CHAMPIONS = new Set([
    "ahri",
    "ashe",
    "blitzcrank",
    "elise",
    "jax",
    "leblanc",
    "leesin",
    "leona",
    "lissandra",
    "lux",
    "morgana",
    "nautilus",
    "neeko",
    "pyke",
    "rakan",
    "renata",
    "sejuani",
    "syndra",
    "thresh",
    "twistedfate",
    "vi",
    "viego",
])

export const DIVE_CHAMPIONS = new Set([
    "akali",
    "alistar",
    "camille",
    "diana",
    "galio",
    "hecarim",
    "irelia",
    "jarvaniv",
    "kaisa",
    "leesin",
    "leona",
    "malphite",
    "nautilus",
    "nocturne",
    "rakan",
    "rell",
    "renekton",
    "sejuani",
    "sylas",
    "vi",
    "viego",
    "wukong",
    "yasuo",
    "yone",
])

export const PEEL_CHAMPIONS = new Set([
    "alistar",
    "braum",
    "ivern",
    "janna",
    "karma",
    "lulu",
    "milio",
    "nami",
    "poppy",
    "renata",
    "rakan",
    "seraphine",
    "tahmkench",
    "taric",
    "thresh",
    "zilean",
])

export const SCALING_CHAMPIONS = new Set([
    "aphelios",
    "azir",
    "cassiopeia",
    "corki",
    "gwen",
    "jax",
    "jinx",
    "kaisa",
    "kayle",
    "kogmaw",
    "orianna",
    "ryze",
    "senna",
    "sivir",
    "smolder",
    "tristana",
    "twitch",
    "veigar",
    "viktor",
    "vladimir",
    "xayah",
    "zeri",
])

export const SPLITPUSH_CHAMPIONS = new Set([
    "camille",
    "fiora",
    "gwen",
    "jax",
    "jayce",
    "ksante",
    "renekton",
    "riven",
    "trundle",
    "tryndamere",
    "twistedfate",
    "yone",
])
